server:
  port: 8082


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ddrun/spring-cloud-practice.git
          username:
          password:
#          basedir: config-properties
          search-paths: config-properties/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true




